In [67]:
import numpy as np
from numpy import pi

In [16]:
a = np.arange(20).reshape(4,5)
print(a.ndim)
print(a.shape)

2
(4, 5)


In [17]:
b = np.arange(8).reshape(2,2,2)
print(b.shape)
print(b.ndim)

(2, 2, 2)
3


In [19]:
print(a.itemsize)
display(b.itemsize)

4


4

In [20]:
print(a.size)
print(b.size)

20
8


In [21]:
(a.size)/(a.ndim)

10.0

In [23]:
a = np.array([1,2,2])
print(type(a))
a.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [24]:
a = np.array((1,1,1), dtype = int)

dtype('int32')

In [25]:
np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [26]:
np.ones((3,3,3), dtype = int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [27]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.arange(10,30,1)#create array raning from 10 to 30 with 1 interval

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [33]:
np.arange(10,11, 0.5)

array([10. , 10.5])

In [34]:
np.linspace(1,10, 10)# 1 to 10 with total 10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
np.linspace(1,10*np.pi,10)

array([ 1.        ,  4.37954739,  7.75909479, 11.13864218, 14.51818957,
       17.89773696, 21.27728436, 24.65683175, 28.03637914, 31.41592654])

In [36]:
a = np.arange(8).reshape(2,2,2)
a.shape

(2, 2, 2)

In [37]:
x = np.array([5,10,15,20])
y = np.arange(4)
y

array([0, 1, 2, 3])

In [38]:
z = x-y
z

array([ 5,  9, 13, 17])

In [39]:
y*10

array([ 0, 10, 20, 30])

In [40]:
y**10

array([    0,     1,  1024, 59049], dtype=int32)

In [41]:
1* np.sin(x)

array([-0.95892427, -0.54402111,  0.65028784,  0.91294525])

In [42]:
x>15

array([False, False, False,  True])

In [43]:
x[x>15]

array([20])

In [44]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

In [45]:
A*B #elementwise product

array([[2, 0],
       [0, 4]])

In [46]:
A@B #matrix product

array([[5, 4],
       [3, 4]])

In [47]:
A.dot(B) #matrix product

array([[5, 4],
       [3, 4]])

In [48]:
rg = np.random.default_rng(1)# random number generator

In [49]:
a = rg.random((2,3)) # array with random numbers with shape (2,3)
a.shape

(2, 3)

In [50]:
b = np.ones((2,3))

In [51]:
b *= 3
b

array([[3., 3., 3.],
       [3., 3., 3.]])

In [52]:
b += 9
b

array([[12., 12., 12.],
       [12., 12., 12.]])

In [61]:
np.random.default_rng(1)
a = np.ones((4,6), dtype = int)
b = np.ones((4,6))
a*=3
a

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [62]:
b+= a # b not coverted to integer
b

array([[4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.]])

In [69]:
a = np.ones(3, dtype=np.int32)
a
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [75]:
c = a+b
print(c)
c.dtype.name

[1.         2.57079633 4.14159265]


'float64'

In [74]:
d = np.exp(c * 1j)
print(d)
d.dtype.name

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

In [80]:
a = rg.random((2, 3))
a
print(a.sum())#sum
print(a.min())# minimum
print(a.max())# maximum

3.5624080737423904
0.11586561247077032
0.9172977047909027


In [81]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
print(b.sum(axis = 0)) # sum of each column
print(b.sum(axis =1)) # sum of each row

[12 15 18 21]
[ 6 22 38]


In [87]:
print(b.min(axis = 1))# min of each row
print(b.min(axis =0)) # min of each column

[0 4 8]
[0 1 2 3]


In [89]:
b.cumsum(axis =1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

### Universal functions

In [91]:
b = np.arange(3)
b

array([0, 1, 2])

In [92]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [96]:
print(np.sqrt(b))
c = np.sqrt(b)

[0.         1.         1.41421356]


array([0.        , 1.        , 1.41421356])

In [97]:
np.add(b,c)

array([0.        , 2.        , 3.41421356])

### Indexiing, slicing and iterating

In [99]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [101]:
a[2]

8

In [102]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [104]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [106]:
a[:6:2] = 1000 
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [108]:
a[::-1]# reverse the order

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [109]:
for i in a:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [113]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f, (5,4), dtype = int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [114]:
b[2,3]

23

In [115]:
b[0:5 , 1]

array([ 1, 11, 21, 31, 41])

In [116]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [117]:
b[1:2, :]

array([[10, 11, 12, 13]])

In [118]:
b[-1]

array([40, 41, 42, 43])

In [119]:
c = np.array([[[  0,  1,  2],  
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

c.shape

(2, 2, 3)

In [120]:
c[1, ...] 

array([[100, 101, 102],
       [110, 112, 113]])

In [121]:
c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [122]:
c[0]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [123]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [124]:
c[:,:, 2]

array([[  2,  13],
       [102, 113]])

In [126]:
for i in b:
    print(i)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [127]:
for i in b.flat:
    print(i)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Shape manipulation

In [132]:
a = np.floor(10* rg.random((3,4)))
a

array([[2., 0., 6., 7.],
       [8., 2., 2., 6.],
       [8., 9., 1., 4.]])

In [133]:
a.shape

(3, 4)

In [139]:
print(a.ravel()) # flat
a.ravel().shape

[2. 0. 6. 7. 8. 2. 2. 6. 8. 9. 1. 4.]


(12,)

In [135]:
a.T # transpose

array([[2., 8., 8.],
       [0., 2., 9.],
       [6., 2., 1.],
       [7., 6., 4.]])

In [136]:
a.T.shape

(4, 3)

In [141]:
a.resize((2,6))
a

array([[2., 0., 6., 7., 8., 2.],
       [2., 6., 8., 9., 1., 4.]])

In [145]:
print(a.reshape(3,-1))
print(a.reshape(3,-1).shape)

[[2. 0. 6. 7.]
 [8. 2. 2. 6.]
 [8. 9. 1. 4.]]
(3, 4)


### Staking together different arrays

In [147]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[6., 9.],
       [8., 8.]])

In [148]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[6., 2.],
       [7., 2.]])

In [150]:
stack = np.vstack((a,b))
print(stack)
stack.shape

[[6. 9.]
 [8. 8.]
 [6. 2.]
 [7. 2.]]


(4, 2)

In [151]:
stack = np.hstack((a,b))
print(stack)
stack.shape

[[6. 9. 6. 2.]
 [8. 8. 7. 2.]]


(2, 4)

In [152]:
from numpy import newaxis

In [154]:
c_stack = np.column_stack((a, b))
print(c_stack)
c_stack.shape

[[6. 9. 6. 2.]
 [8. 8. 7. 2.]]


(2, 4)

In [155]:
a = np.array([4, 2])
b = np.array([3,8])

In [156]:
np.column_stack((a,b))

array([[4, 3],
       [2, 8]])

In [157]:
np.hstack((a,b))

array([4, 2, 3, 8])

In [158]:
a[:, newaxis]

array([[4],
       [2]])

In [159]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4, 3],
       [2, 8]])

In [160]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4, 3],
       [2, 8]])

In [163]:
### Splitting 

In [166]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[9., 7., 7., 7., 5., 9., 6., 5., 0., 4., 2., 1.],
       [5., 7., 2., 7., 5., 1., 9., 4., 2., 8., 1., 7.]])

In [167]:
np.hsplit(a, 3)

[array([[9., 7., 7., 7.],
        [5., 7., 2., 7.]]),
 array([[5., 9., 6., 5.],
        [5., 1., 9., 4.]]),
 array([[0., 4., 2., 1.],
        [2., 8., 1., 7.]])]

In [168]:
np.hsplit(a, (3,4))

[array([[9., 7., 7.],
        [5., 7., 2.]]),
 array([[7.],
        [7.]]),
 array([[5., 9., 6., 5., 0., 4., 2., 1.],
        [5., 1., 9., 4., 2., 8., 1., 7.]])]

In [169]:
def f(x):
    print(id(x))

In [170]:
id(a) # unique identifieer

1207685329424

In [172]:
f(a)

1207685329424


In [175]:
c = a.view()
c is a

False

In [176]:
c.flags.owndata

False

In [177]:
c.shape

(2, 12)

In [180]:
c.reshape((12,2))

array([[9., 7.],
       [7., 7.],
       [5., 9.],
       [6., 5.],
       [0., 4.],
       [2., 1.],
       [5., 7.],
       [2., 7.],
       [5., 1.],
       [9., 4.],
       [2., 8.],
       [1., 7.]])

In [182]:
c[0,4] = 1234
c

array([[9.000e+00, 7.000e+00, 7.000e+00, 7.000e+00, 1.234e+03, 9.000e+00,
        6.000e+00, 5.000e+00, 0.000e+00, 4.000e+00, 2.000e+00, 1.000e+00],
       [5.000e+00, 7.000e+00, 2.000e+00, 7.000e+00, 5.000e+00, 1.000e+00,
        9.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 1.000e+00, 7.000e+00]])

In [184]:
s = a[:, 1:3]
s

array([[7., 7.],
       [7., 2.]])

In [187]:
s[:] =10
s

array([[10., 10.],
       [10., 10.]])

In [188]:
d = a.copy()
d is a

False

In [189]:
d.base is a

False

In [193]:
d[0,0] = 333
d

array([[3.330e+02, 1.000e+01, 1.000e+01, 7.000e+00, 1.234e+03, 9.000e+00,
        6.000e+00, 5.000e+00, 0.000e+00, 4.000e+00, 2.000e+00, 1.000e+00],
       [5.000e+00, 1.000e+01, 1.000e+01, 7.000e+00, 5.000e+00, 1.000e+00,
        9.000e+00, 4.000e+00, 2.000e+00, 8.000e+00, 1.000e+00, 7.000e+00]])

In [195]:
a = np.arange(int(1e8))
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [197]:
b = a[:100].copy()
del a

In [ ]:
### Indexing arrays of indices

In [198]:
a = np.arange(12)**2 
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [200]:
i = np.array([1,1,3,8,5])
i

array([1, 1, 3, 8, 5])

In [203]:
j = np.array([[3,4], [9,7]])
j

array([[3, 4],
       [9, 7]])

In [204]:
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [205]:
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white

In [206]:
image = np.array([[0, 1, 2, 0],  # each value corresponds to a color in the palette
                  [0, 3, 4, 0]])

In [207]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [208]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
i = np.array([[0,1], [1,2]])
j = np.array([[2, 1],
              [3, 3]])

In [212]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [213]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [214]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [215]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [216]:
l = (i,j)
l

(array([[0, 1],
        [1, 2]]),
 array([[2, 1],
        [3, 3]]))

In [217]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [220]:
s = np.array([i,j])
print(s)
s.shape

[[[0 1]
  [1 2]]

 [[2 1]
  [3 3]]]


(2, 2, 2)

In [221]:
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [222]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [224]:
time = np.linspace(20, 145,5)
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [226]:
data = np.sin(np.arange(20)).reshape(5,4)
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [228]:
ind = data.argmax(axis = 0)# maximu for each series
ind

array([2, 0, 3, 1], dtype=int64)

In [230]:
time_max = time[ind]

In [231]:
data_max = data[ind, range(data.shape[1])]

In [232]:
data_max == data.max(axis =0)

array([ True,  True,  True,  True])

In [233]:
np.all(data_max == data.max(axis =0))

True

In [237]:
a = np.arange(5)
a


array([0, 1, 2, 3, 4])

In [238]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [240]:
a = np.arange(5)
a
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

In [243]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [242]:
a[[0, 0, 2]] += 1
a

array([1, 1, 3, 3, 4])

### Indexing boolean arrays

In [252]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [247]:
b = a>5
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [257]:
a[a == 10] =200
a

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9, 200,  11]])

In [248]:
a[b]

array([ 6,  7,  8,  9, 10, 11])

In [250]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 5, 0, 0],
       [0, 0, 0, 0]])